# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd18693aa153a5f3202507f969669a04d3fac146631bc138154118f80e9e908966b3aec51b0116fbbfe0e9071305111a3ae3437f92365d865810e775992832a7

test:
  secret_key_base: 05be1a5da2a150d694f93e5dd158cda63f11b4db27400fdf9f538fa2a83a82e0650ba57d4739fa6f53420b66520e519681ec385e4c659f0a3b0387189b933c86

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
